// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectRole string

const (
	ProjectRoleOwner  ProjectRole = "owner"
	ProjectRoleEditor ProjectRole = "editor"
	ProjectRoleViewer ProjectRole = "viewer"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"project_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type Project struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	Fps       int32              `json:"fps"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID string             `json:"project_id"`
	UserID    string             `json:"user_id"`
	Role      ProjectRole        `json:"role"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
}

type ProjectOp struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	UserID    string             `json:"user_id"`
	Seq       int64              `json:"seq"`
	OpType    string             `json:"op_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectSnapshot struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	Version   int32              `json:"version"`
	Document  []byte             `json:"document"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
