// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID string      `json:"project_id"`
	UserID    string      `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, fps, width, height, created_at, updated_at
`

type CreateProjectParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Fps,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO project_snapshots (id, project_id, version, document)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, version, document, created_at
`

type CreateSnapshotParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Version   int32  `json:"version"`
	Document  []byte `json:"document"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (ProjectSnapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ID,
		arg.ProjectID,
		arg.Version,
		arg.Document,
	)
	var i ProjectSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, project_id, version, document, created_at
FROM project_snapshots
WHERE project_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, projectID string) (ProjectSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, projectID)
	var i ProjectSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, owner_id, fps, width, height, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Fps,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, invited_at
FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role, pm.invited_at, u.display_name, u.email
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
ORDER BY pm.invited_at
`

type ListProjectMembersRow struct {
	ProjectID   string             `json:"project_id"`
	UserID      string             `json:"user_id"`
	Role        ProjectRole        `json:"role"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.InvitedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.owner_id, p.fps, p.width, p.height, p.created_at, p.updated_at
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1
ORDER BY p.updated_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Fps,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}
